<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SchemesTableSeeder extends Seeder
{
    public function run()
    {
        // Department IDs corresponding to your list
        $departmentIds = [
            'Department of Agricultural Research and Education' => 1,
            'Department of Agriculture and Farmers Welfare' => 2,
            'Department of Animal Husbandry and Dairying' => 3,
            'Department of Atomic Energy' => 4,
            'Department of BioTechnology' => 5,
            'Department of Chemicals and Petrochemicals' => 6,
            'Department of Commerce' => 7,
            'Department of Drinking Water and Sanitation' => 8,
            'Department of Empowerment of Persons with Disabilities' => 9,
            'Department of Ex Servicemen Welfare' => 10,
            'Department of Fertilizers' => 11,
            'Department of Financial Services' => 12,
            'Department of Fisheries' => 13,
            'Department of Food and Public Distribution' => 14,
            'Department of Health and Family Welfare' => 15,
            'Department of Health Research' => 16,
            'Department of Higher Education' => 17,
            'Department of Home' => 18,
            'Department of Internal Security' => 19,
            'Department of Jammu and Kashmir and Ladakh Affairs' => 20,
            'Department of Pharmaceuticals' => 21,
            'Department of Public Enterprises' => 22,
            'Department of Rural Development' => 23,
            'Department of School Education and Literacy' => 24,
            'Department of Science and Technology' => 25,
            'Department of Scientific and Industrial Research' => 26,
            'Department of Social Justice and Empowerment' => 27,
            'Department of Space' => 28,
            'Department of Sports' => 29,
            'Department of Water Resources, River Development and Ganga Rejuvenation' => 30,
            'Department of Youth Affairs' => 31,
            'Ministry of AYUSH' => 32,
            'Ministry of Culture' => 33,
            'Ministry of Development of North Eastern Region' => 34,
            'Ministry of Earth Science' => 35,
            'Ministry of Electronics and Information Technology' => 36,
            'Ministry of Environment Forest and Climate Change' => 37,
            'Ministry of External Affairs' => 38,
            'Ministry of Heavy Industries' => 39,
            'Ministry of Housing and Urban Affairs' => 40,
            'Ministry of Information and Broadcasting' => 41,
            'Ministry of Labour and Employment' => 42,
            'Ministry of Micro Small and Medium Enterprises' => 43,
            'Ministry of Minority Affairs' => 44,
            'Ministry of New and Renewable Energy' => 45,
            'Ministry of Petroleum and Natural Gas' => 46,
            'Ministry of Railways' => 47,
            'Ministry of Skill Development and Entrepreneurship' => 48,
            'Ministry of Statistics and Programme Implementation' => 49,
            'Ministry of Textiles' => 50,
            'Ministry of Tourism' => 51,
            'Ministry of Tribal Affairs' => 52,
            'Ministry of Women and Child Development' => 53,

            // Add more departments and their IDs if needed
        ];

        $schemes = [
            // (ID: 1)
            ['name' => 'Agricultural Extension', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - National Talent Scholarship UG', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - Merit Cum Means scholarship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - Post Matric Scholarship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - Students READY', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - ICAR Emeritus Scientist', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - ICAR Emeritus Professor', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - Netaji Subhas ICAR International Fellowship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - ICAR Junior Research Fellowship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - ICAR Senior Research Fellowship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - India-Africa Fellowship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - India-Afghanistan Fellowship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - National Talent Scholarship PG', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AS_NDRI_Institute Scholarship for M.Sc. and Ph.D.', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'FS - CIFE - Institutional Fellowship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'CS- IARI Scholarship', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AgEdn - ICAR National Professor and National Fellow', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'IASRI Scholarship for MSc and PhD', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],
            ['name' => 'AS_IVRI_Institute Scholarship for M.V.Sc. and Ph.D.', 'department_id' => $departmentIds['Department of Agricultural Research and Education']],

            //  (ID: 2)
            ['name' => 'Krishi Unnati Yojana (KUY)-MOVCDNER', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Pradhan Mantri Fasal Bima Yojna', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Sub-Mission on Seeds and Planting Material', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'National Food Security Mission - NFSM', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Sub Mission on Agriculture Mechanization-Centrally Sponsored', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'NMSA-Rainfed Area Development', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'RKVY (RAFTAAR)', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Mission for Integrated Development of Horticulture', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Per Drop More Crop', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Agri Clinics and Agri Business Centres ACABC', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Agriculture Technology Management Agency (ATMA) - Extension Functionaries', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Agriculture Technology Management Agency (ATMA)- Farmers', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'Sub Mission on Agriculture Mechanization-Central Sector', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'PM KISAN', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],
            ['name' => 'National Mission on Edible Oil-Oilpalm', 'department_id' => $departmentIds['Department of Agriculture and Farmers Welfare']],

            // (ID: 3)
            ['name' => 'Livestock Health and Diseases Control', 'department_id' => $departmentIds['Department of Animal Husbandry and Dairying']],
            //(ID: 4)
            ['name' => 'Raja Ramanna Centre for Advanced technology RRCAT-Opportunities of Projects in RRCAT for Students', 'department_id' => $departmentIds['Department of Atomic Energy']],
            ['name' => 'Advanced Centre for Treatment, Research, and Education in Cancer ACTREC-Phd Programme', 'department_id' => $departmentIds['Department of Atomic Energy']],
            ['name' => 'IMSc- Phd Programme', 'department_id' => $departmentIds['Department of Atomic Energy']],
            //(ID: 5)
            ['name' => 'Junior Research Fellowship', 'department_id' => $departmentIds['Department of BioTechnology']],
            ['name' => 'Research Associates', 'department_id' => $departmentIds['Department of BioTechnology']],
            // (ID: 6)
            ['name' => 'Bhopal Gas Leak Disaster', 'department_id' => $departmentIds['Department of Chemicals and Petrochemicals']],

            //  (ID: 7)
            ['name' => 'Coffee Board', 'department_id' => $departmentIds['Department of Commerce']],
            ['name' => 'Tea Board', 'department_id' => $departmentIds['Department of Commerce']],
            ['name' => 'Rubber Board', 'department_id' => $departmentIds['Department of Commerce']],
            ['name' => 'Spice board', 'department_id' => $departmentIds['Department of Commerce']],
            ['name' => 'APEDA', 'department_id' => $departmentIds['Department of Commerce']],
            ['name' => 'MPEDA', 'department_id' => $departmentIds['Department of Commerce']],
            //  (ID: 8)
            ['name' => 'Swachh Bharat Mission Gramin', 'department_id' => $departmentIds['Department of Drinking Water and Sanitation']],
            //  (ID: 9)
            ['name' => 'Deen Dayal Disabled Rehabilitation Scheme', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'Assistance to Disabled Persons for Purchase, Fitting of Aids, Appliances', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'National Fellowship for Students with Disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'National Overseas Scholarship for students with disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'Scholarship for Top Class Education for students with disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'National Action Plan for skill development for persons with disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'Incentives to private sector employers for providing employment to persons with disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'Pre-matric scholarship for Persons with disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            ['name' => 'Free Coaching for Students with Disabilities', 'department_id' => $departmentIds['Department of Empowerment of Persons with Disabilities']],
            //  (ID: 10)
            ['name' => 'Prime Ministers Scholarship Scheme PMSS', 'department_id' => $departmentIds['Department of Ex Servicemen Welfare']],
            ['name' => 'Raksha Mantri Ex-servicemen Welfare Fund (RMEWF)', 'department_id' => $departmentIds['Department of Ex Servicemen Welfare']],
            //  (ID: 11)
            ['name' => 'Fertilizer Subsidy Scheme', 'department_id' => $departmentIds['Department of Fertilizers']],
            //  (ID: 12)
            ['name' => 'Atal Pension Yojana', 'department_id' => $departmentIds['Department of Financial Services']],
            ['name' => 'Varishtha Pension Bima Yojana', 'department_id' => $departmentIds['Department of Financial Services']],
            ['name' => 'Pradhan Mantri Vaya Vandana Yojana', 'department_id' => $departmentIds['Department of Financial Services']],
            //(ID: 13) 
            ['name' => 'Pradhan Mantri Matsya Sampada Yojana', 'department_id' => $departmentIds['Department of Fisheries']],

            // (ID: 14)
            ['name' => 'Direct Cash Transfer for food grains', 'department_id' => $departmentIds['Department of Food and Public Distribution']],
            ['name' => 'DBT Kind - PDS operations in 34 states and UTs', 'department_id' => $departmentIds['Department of Food and Public Distribution']],
            // Department of Animal Husbandry and Dairying (ID: 15)
            ['name' => 'Janani suraksha yojana', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'ASHA incentives', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'Family Planning Compensation schemes', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'Payments to contractual staff', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'Janani Shishu Suraksha Karyakram', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'NIKSHAY - Tribal TB Patients', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'NIKSHAY - DOT Provider Honorarium', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'NIKSHAY - TB Notification incentive for Private Sector', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'NIKSHAY - TB patient incentive for nutritional support', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'Ayushman Bharat -Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            ['name' => 'National Covid-19 Vaccination Programme', 'department_id' => $departmentIds['Department of Health and Family Welfare']],
            // Department of Animal Husbandry and Dairying (ID: 16)
            ['name' => 'Fellowship Programmes Under The Human Resource Development For Health Research', 'department_id' => $departmentIds['Department of Health Research']],
            ['name' => 'ICMR-Junior Research Fellowship', 'department_id' => $departmentIds['Department of Health Research']],
            ['name' => 'ICMR-Post Doctoral Fellowship', 'department_id' => $departmentIds['Department of Health Research']],
            ['name' => 'ICMR-Short Term Studentship', 'department_id' => $departmentIds['Department of Health Research']],
            // Department of Animal Husbandry and Dairying (ID: 17)
            ['name' => 'Pradhan Mantri Uchchatar Shiksha Protsahan (PM -USP) Central Sector Scheme of Scholarship for College and University students', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Ishan Uday Special Scholarship Scheme for North Eastern Region', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'P.G. Scholarship for Professional Courses for SC/ST candidates', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'P.G. Indira Gandhi Scholarship For Single Girl Child', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'P.G. Scholarship for University Rank Holders', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Junior Research Fellowship in Science, Humanities and Social Sciences', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Swami Vivekananda Single Girl Child Fellowship for Research in Social Sciences', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'BSRFellowship', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Post-Doctoral Fellowship for SC/ST Candidates', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Dr S Radhakrishnan Postdoctoral Fellowship in Humanities and Social Science', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Post Doctoral Fellowship for Women', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Dr D S Kothari Post Doctoral Fellowship', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Emeritus Fellowship', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'P.G. Scholarship for GATE/GPAT qualified students for pursuing M.Tech/ M.E./M.Pharma- UGC', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Pragati Scholarship for girls in Degree Colleges', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Pragati Scholarship for girls Diploma Institutes', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Saksham scholarship for differently abled students of Degree Colleges', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Saksham scholarship for differently abled students of Diploma Institutes', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Pradhan Mantri Uchchatar Shiksha Protsahan (PM -USP) Special Scholarship Scheme for Jammu & Kashmir and Ladakh', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'QIP for faculty deputed for M.Tech/ Ph.D studies at QIP Centers', 'department_id' => $departmentIds['Department of Home']],
            ['name' => 'Pradhan Mantri Uchchatar Shiksha Protsahan (PM -USP) Central Sector Interest Subsidy Scheme', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'P.G. Scholarship For GATE/GPAT Qualified Students For Pursuing M.Tech/M.E./M.Pharma - AICTE', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'National Doctoral Fellowship (NDF)', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Programme for Apprenticeship', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Indian Knowledge Systems', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'AICTE - Swanath Scholarship Scheme - Degree', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'AICTE - Swanath Scholarship Scheme - Diploma', 'department_id' => $departmentIds['Department of Higher Education']],
            ['name' => 'Savitribai Jyotirao Phule Fellowship for Single Girl Child', 'department_id' => $departmentIds['Department of Higher Education']],
            //  (ID: 18)
            ['name' => 'Swatantrata Sainik Samman Pension Scheme', 'department_id' => $departmentIds['Department of Home']],
            ['name' => 'Grant in Aid to Tripura and Mizoram for Rehabilitation of Bru Migrants', 'department_id' => $departmentIds['Department of Home']],
            ['name' => 'Relief and Rehabilitation Assistance to Sri Lankan Refugees in the Refugee Camps', 'department_id' => $departmentIds['Department of Home']],
            ['name' => 'Census of India 2021 and Updation of National Population Register', 'department_id' => $departmentIds['Department of Home']],
            ['name' => 'Enhanced Compensation to 1984 Sikh Riots', 'department_id' => $departmentIds['Department of Home']],
            //  (ID: 19)
            ['name' => 'Prime Minister Scholarship Scheme', 'department_id' => $departmentIds['Department of Internal Security']],
            ['name' => 'Central Scheme for Assistance to Civilian Victims (CSACV)', 'department_id' => $departmentIds['Department of Internal Security']],
            //  (ID: 20)
            ['name' => 'Security Related Expenditure - Relief and Rehabilitation of Kashmiri Migrants', 'department_id' => $departmentIds['Department of Jammu and Kashmir and Ladakh Affairs']],
            ['name' => 'PM Assistance to DPs of POJK', 'department_id' => $departmentIds['Department of Jammu and Kashmir and Ladakh Affairs']],
            ['name' => 'Relief and Rehabilitation for Migrants and Repatriates', 'department_id' => $departmentIds['Department of Jammu and Kashmir and Ladakh Affairs']],
            //  (ID: 21)
            ['name' => 'Pradhan Mantri Bhartiya Jan Aushadhi Pariyojana (PMBJP)', 'department_id' => $departmentIds['Department of Pharmaceuticals']],
            ['name' => 'Scholarship to NIPER Students', 'department_id' => $departmentIds['Department of Pharmaceuticals']],
            //  (ID: 22)
            ['name' => 'Counselling, Retraining and Redeployment Scheme', 'department_id' => $departmentIds['Department of Public Enterprises']],
            ['name' => 'Scheme of Research, Development and Consultancies on Generic Issues of Public Sector Enterprises', 'department_id' => $departmentIds['Department of Public Enterprises']],
            //  (ID: 23)
            ['name' => 'Deen Dayal Upadhyay Grameen Kaushalya Yojna', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'Pradhan Mantri Awas Yojna Grameen', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'Mahatma Gandhi NREGA', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'Indira Gandhi National Widow Pension Scheme (IGNWPS)', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'Indira Gandhi National Disability Pension Scheme (IGNDPS)', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'DAY-NRLM', 'department_id' => $departmentIds['Department of Rural Development']],
            ['name' => 'National Family Benefit Scheme', 'department_id' => $departmentIds['Department of Rural Development']],
            //  (ID: 24)
            ['name' => 'National Means-cum-Merit Scholarship Scheme', 'department_id' => $departmentIds['Department of School Education and Literacy']],
            ['name' => 'National Scheme of Incentive to Girls for Secondary Education', 'department_id' => $departmentIds['Department of School Education and Literacy']],
            ['name' => 'Stipend for Disabled Girls under IEDSS Component of Samagra Shiksha', 'department_id' => $departmentIds['Department of School Education and Literacy']],
            ['name' => 'Samagra Shiksha (Interventions of Uniform/Text Books)', 'department_id' => $departmentIds['Department of School Education and Literacy']],
            ['name' => 'Pradhan Mantri Poshan Shakti Nirman (PM-POSHAN)', 'department_id' => $departmentIds['Department of School Education and Literacy']],
            ['name' => 'Kind Benefit under IEDSS Component of Samagra Shiksha', 'department_id' => $departmentIds['Department of School Education and Literacy']],
            //  (ID: 25)
            ['name' => 'Disha Programme for Women in Science', 'department_id' => $departmentIds['Department of Science and Technology']],
            ['name' => 'Alliance and R and D Mission - INSPIRE Award', 'department_id' => $departmentIds['Department of Science and Technology']],
            ['name' => 'Alliance and R and D Mission - INSPIRE Scholarship', 'department_id' => $departmentIds['Department of Science and Technology']],
            ['name' => 'Alliance and R and D Mission - INSPIRE Fellowship', 'department_id' => $departmentIds['Department of Science and Technology']],
            ['name' => 'Alliance and R and D Mission - INSPIRE Faculty Award', 'department_id' => $departmentIds['Department of Science and Technology']],
            ['name' => 'Alliance and R and D Mission - INSPIRE Internship', 'department_id' => $departmentIds['Department of Science and Technology']],
            //  (ID: 26)
            ['name' => 'Promoting Innovations in Individuals Start-ups and MSMEs - PRISM', 'department_id' => $departmentIds['Department of Scientific and Industrial Research']],
            ['name' => 'National S&T Human Resource Development', 'department_id' => $departmentIds['Department of Scientific and Industrial Research']],
            ['name' => 'Technology Development Utilization Program for Women', 'department_id' => $departmentIds['Department of Scientific and Industrial Research']],
            //  (ID: 27)
            ['name' => 'Pre-Matric Scholarship Scheme for Scheduled Castes and Others', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Centrally Sponsored Scheme Of Post Matric Scholarships To The Students Belonging To Scheduled Castes For Studies In India', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme of National Fellowship for providing scholarships to Scheduled Caste students to pursue programmes in Higher Education such as M.Phil. and Ph.D.', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'PM YASASVI - Post-Matric Scholarship to OBC, EBC and DNT', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'PM YASASVI - Pre-Matric Scholarship to OBC, EBC and DNT', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme of National Fellowship for OBC Students', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme of Free Coaching for SC and OBC Students', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'NAMASTE', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Centrally Sponsored Scheme For Implementation Of Protection Of Civil Rights Act 1955 And Scheduled Castes And Scheduled Castes And Scheduled Tribes (Prevention Of Atrocities Act, 1989)', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Scheme of Grant-in-aid to Voluntary and other Organisations working for Scheduled Castes', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Dr Ambedkar Central Sector Scheme of Interest Subsidy on Educational Loans for Overseas Studies for Other Backward Classes (OBCs) and Economically Backward Classes (EBCs)', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme of Assistance for Prevention of Alcoholism and Substance (Drugs) Abuse and for Social Defence Services', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Integrated Programme for Older Persons', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme Of Top Class Education For SC Students', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Vanchit Ikai Samuhaur Vargon ki Arthik Sahayata (VISVAS) Yojana', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'National Overseas Scholarship (NOS)', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'PM DAKSH Scheme', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Scholarship for PM care Children', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme of Top Class College Education for OBC, EBC and DNT Students', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Central Sector Scheme of Top Class School Education for OBC, EBC and DNT Students', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            ['name' => 'Pradhan Mantri Anusuchit Jati Abhyuday Yojana', 'department_id' => $departmentIds['Department of Social Justice and Empowerment']],
            //  (ID: 28)
            ['name' => 'Master Control Facility - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Indian Space Research Organization Headquarters - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'ISRO Propulsion Complex - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Satish Dhawan Space Centre-SHAR - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'ISRO Telemetry, Tracking and Command Network - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'UR Rao Satellite Centre - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Liquid Propulsion Systems Centre - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Vikram Sarabhai Space Centre - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Space Applications Centre - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'National Remote Sensing Centre - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Indian Institute of Remote Sensing - Scholarships and Stipends', 'department_id' => $departmentIds['Department of Space']],
            ['name' => 'Indian Institute of Space Science and Technology - Assistanceship and Fellowships', 'department_id' => $departmentIds['Department of Space']],
            // (ID: 29)
            ['name' => 'Khelo India', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'Assistance to National Sports Federations', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'Scheme for Human Resource Development in Sports', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'Sports Authority of India', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'Lakshmibai National Institute of Physical Education', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'National Welfare Fund for Sportspersons', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'National Sports Development Fund', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'Special Cash Awards to Medal Winners in International Sports Events', 'department_id' => $departmentIds['Department of Sports']],
            ['name' => 'Pension to Meritorious Sportspersons', 'department_id' => $departmentIds['Department of Sports']],

            ['name' => 'R&D Programme in Water Sector', 'department_id' => $departmentIds['Department of Water Resources, River Development and Ganga Rejuvenation']],

            ['name' => 'National Youth Corps', 'department_id' => $departmentIds['Department of Youth Affairs']],
            ['name' => 'Youth Hostels', 'department_id' => $departmentIds['Department of Youth Affairs']],
            ['name' => 'IC - International Youth Exchange Programmes', 'department_id' => $departmentIds['Department of Youth Affairs']],
            ['name' => 'Assistance to Scouting and Guiding Organizations', 'department_id' => $departmentIds['Department of Youth Affairs']],
            ['name' => 'RGNIYD - Academic, Training and Capacity Building Programmes', 'department_id' => $departmentIds['Department of Youth Affairs']],
            ['name' => 'RGNIYD - Scholarships to Students', 'department_id' => $departmentIds['Department of Youth Affairs']],

            ['name' => 'Rashtriya Ayurveda Vidyapeeth', 'department_id' => $departmentIds['Ministry of AYUSH']],
            ['name' => 'National AYUSH Mission - Medicines under AYUSH Services', 'department_id' => $departmentIds['Ministry of AYUSH']],
            ['name' => 'Promotion of International Co-operation in AYUSH', 'department_id' => $departmentIds['Ministry of AYUSH']],

            ['name' => 'Award of Scholarships to Young Artists in Different Cultural Fields', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Award of Junior Fellowship to Outstanding Artistes/Persons in the Field of Culture', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Award of Tagore National Fellowship for Cultural Research', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Scheme for Pension and Medical Aid to Artistes', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Repertory Grant', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Cultural Function and Production Grant', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Financial Assistance to Cultural Organisations with National Presence', 'department_id' => $departmentIds['Ministry of Culture']],
            ['name' => 'Award of Senior Fellowship to Outstanding Artistes/Persons in the Field of Culture', 'department_id' => $departmentIds['Ministry of Culture']],

            ['name' => 'Scheme of North Eastern Council of Financial Support to the Students of North East Region', 'department_id' => $departmentIds['Ministry of Development of North Eastern Region']],

            ['name' => 'Polar Science and Cryosphere (PACER)', 'department_id' => $departmentIds['Ministry of Earth Science']],
            ['name' => 'Research, Education and Training Outreach (REACHOUT)', 'department_id' => $departmentIds['Ministry of Earth Science']],

            ['name' => 'Reimbursement of Training Fees under Scheduled Caste Sub Plan/Tribal Sub Plan', 'department_id' => $departmentIds['Ministry of Electronics and Information Technology']],
            ['name' => 'FutureSkills PRIME (Programme for Re-skilling/Up-skilling of IT Manpower for Employability)', 'department_id' => $departmentIds['Ministry of Electronics and Information Technology']],
            ['name' => 'Visvesvaraya PhD Scheme for Electronics and IT Phase II', 'department_id' => $departmentIds['Ministry of Electronics and Information Technology']],

            ['name' => 'Green India Mission National Afforestation Programme', 'department_id' => $departmentIds['Ministry of Environment Forest and Climate Change']],
            ['name' => 'Project Tiger', 'department_id' => $departmentIds['Ministry of Environment Forest and Climate Change']],
            ['name' => 'Project Elephant', 'department_id' => $departmentIds['Ministry of Environment Forest and Climate Change']],
            ['name' => 'Integrated Development of Wildlife Habitats', 'department_id' => $departmentIds['Ministry of Environment Forest and Climate Change']],

            ['name' => 'ICCR Scholarship', 'department_id' => $departmentIds['Ministry of External Affairs']],

            ['name' => 'Demand Incentive Delivery Mechanism under FAME India Scheme', 'department_id' => $departmentIds['Ministry of Heavy Industries']],
            ['name' => 'Issue of GST Concession Certificate on Purchase of Car by Physically Handicapped Persons', 'department_id' => $departmentIds['Ministry of Heavy Industries']],

            ['name' => 'Credit Link Subsidy Scheme (CLSS)', 'department_id' => $departmentIds['Ministry of Housing and Urban Affairs']],
            ['name' => 'DAY-NULM', 'department_id' => $departmentIds['Ministry of Housing and Urban Affairs']],
            ['name' => 'State and UT Grants under PMAY Urban', 'department_id' => $departmentIds['Ministry of Housing and Urban Affairs']],
            ['name' => 'Swachh Bharat Mission Urban', 'department_id' => $departmentIds['Ministry of Housing and Urban Affairs']],
            ['name' => 'PM Street Vendor Atmanirbhar Nidhi (PM SVANidhi)', 'department_id' => $departmentIds['Ministry of Housing and Urban Affairs']],

            ['name' => 'Journalist Welfare Scheme', 'department_id' => $departmentIds['Ministry of Information and Broadcasting']],
            ['name' => 'Scholarship Scheme of Satyajit Ray Film and Television Institute, Kolkata', 'department_id' => $departmentIds['Ministry of Information and Broadcasting']],

            ['name' => 'Employees Pension Scheme for EPF Pensioners', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Grants to VV Giri National Labour Institute (VVGNLI)', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Grants to Dattopant Thengdi National Board for Workers Education and Development (DTNBWED)', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Rehabilitation Assistance under the Scheme of Rehabilitation of Bonded Labour', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Stipend to Differently Abled Candidates under the Scheme of Vocational Rehabilitation Centres for Handicapped', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Stipend to Trainees under the Scheme of Welfare of SC/ST Job-Seekers through Coaching, Guidance and Vocational Training', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Stipend to Children in the Special Schools under the National Child Labour Project (NCLP)', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Revised Integrated Housing Scheme (RIHS) - 2016 for Beedi, IOMC, LSDM, CINE Workers', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Family Pension-cum-Life Assurance and Deposit Linked Insurance Schemes for the Plantation Workers in Assam', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Financial Assistance for Education for the Wards of Beedi, Cine, IOMC, LSDM Workers', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Employees Pension Scheme for EPF Members', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'National Pension Scheme for Traders and Self Employed Persons [erstwhile Pradhan Mantri Laghu Vyapari Maan-dhan (PM-LVM) Yojana]', 'department_id' => $departmentIds['Ministry of Labour and Employment']],
            ['name' => 'National Database for Unorganised Workers', 'department_id' => $departmentIds['Ministry of Labour and Employment']],

            ['name' => 'PMEGP (Prime Minister\'s Employment Generation Programme)', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'MMDA Grant to Khadi Institutions', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'SFURTI - SI', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'IC Schemes', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'Entrepreneurship and Skill Development Programme (ESDP)', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'National Awards', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'Coir Vikas Yojana', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'ATI Scheme (Training Component)', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],
            ['name' => 'PM Vishwakarma', 'department_id' => $departmentIds['Ministry of Micro Small and Medium Enterprises']],

            ['name' => 'Skill Development Initiatives', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Maulana Azad National Fellowship for Minority Students', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Merit-cum-Means based Scholarship for Professional and Technical Courses for Minorities', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Pre-Matric Scholarship for Minorities', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Post-Matric Scholarship for Minorities', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Nai Udaan - Support for Minority Students Clearing Prelims Conducted by UPSC, SSC, State Public Service Commissions and Staff Selection Commission', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Upgrading the Skills and Training in Traditional Arts Crafts for Development (USTTAD)', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Free Coaching Allied Scheme for Minorities', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Nai Roshni', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Nai Manzil', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Padho Pradesh - Interest subsidy on educational loans for Overseas Studies', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Begum Hazrat Mahal National Scholarship Scheme', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'Scheme for containing population decline of small minority community', 'department_id' => $departmentIds['Ministry of Minority Affairs']],
            ['name' => 'PM VIKAS Committed Liabilities', 'department_id' => $departmentIds['Ministry of Minority Affairs']],


            ['name' => 'National Renewable Energy Fellowship Programme and National Solar Science Fellowship Programme', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'New National Biogas and Organic Manure Programme (NNBOMP)', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'Off-grid and Decentralized Solar PV Applications Programme', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'Grid-connected Roof-top Solar Projects implemented on an individual house of capacity of 3 kW and above', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'Fellowship Component of R&D Projects Sponsored by the Ministry', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'Short Term Training Programme Component of HRD Programme', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan Scheme', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],
            ['name' => 'PM-SURYA Ghar Muft Bijli Yojana', 'department_id' => $departmentIds['Ministry of New and Renewable Energy']],

            ['name' => 'PAHAL', 'department_id' => $departmentIds['Ministry of Petroleum and Natural Gas']],
            ['name' => 'Pradhan Mantri Ujjwala Yojana', 'department_id' => $departmentIds['Ministry of Petroleum and Natural Gas']],
            ['name' => 'DBT-K', 'department_id' => $departmentIds['Ministry of Petroleum and Natural Gas']],

            ['name' => 'Prime Minister\'s Scholarship Scheme for Railway Protection Force (RPF)', 'department_id' => $departmentIds['Ministry of Railways']],

            ['name' => 'National Apprenticeship Promotion Scheme', 'department_id' => $departmentIds['Ministry of Skill Development and Entrepreneurship']],
            ['name' => 'Skill Acquisition and Knowledge Awareness for Livelihood Promotion (SANKALP)', 'department_id' => $departmentIds['Ministry of Skill Development and Entrepreneurship']],
            ['name' => 'Pradhan Mantri Kaushal Vikas Yojana', 'department_id' => $departmentIds['Ministry of Skill Development and Entrepreneurship']],

            ['name' => 'Stipend to students in Indian Statistical Institute', 'department_id' => $departmentIds['Ministry of Statistics and Programme Implementation']],
            ['name' => 'Fellowship to research scholars in Indian Statistical Institute', 'department_id' => $departmentIds['Ministry of Statistics and Programme Implementation']],

            ['name' => 'Powerloom Group Workshed Scheme', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Scheme for In-situ Upgradation of Plain Powerloom', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Scheme for Development of Silk Industry', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Samarth Scheme', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Comprehensive Handicrafts Cluster Development Programme', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Raw Material Supply Scheme', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Amended Technology Upgradations Fund', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Pradhan Mantri Credit Scheme for Powerloom Weavers', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Human Resource Development (HRD) And Promotional Activities Scheme - Training Programme in Scientific Sheep Rearing/Artificial Insemination/Manufacturing of Woollen Items/Machine Shearing etc.', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'National Handloom Development Programme', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'National Handicrafts Development Programme', 'department_id' => $departmentIds['Ministry of Textiles']],
            ['name' => 'Price Support Operation for Cotton Procurement by CCI', 'department_id' => $departmentIds['Ministry of Textiles']],

            ['name' => 'Capacity Building for Service Providers', 'department_id' => $departmentIds['Ministry of Tourism']],

            ['name' => 'Pre-Matric Scholarship Scheme for ST students', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'Post-Matric Scholarship Scheme for ST students', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'National Fellowship and Scholarship for Higher Education for ST students (for FELLOWSHIP)', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'National Fellowship and Scholarship for Higher Education for ST students (for SCHOLARSHIP)', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'National Overseas Scholarship Scheme', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'Institutional Support for Development and Marketing of Tribal Products', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'Vocational Training Centres in Tribal Areas', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'Scheme of Development of Particularly Vulnerable Tribal Groups', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],
            ['name' => 'Scheme of Grant in Aid to Voluntary Organizations working for Welfare of STs', 'department_id' => $departmentIds['Ministry of Tribal Affairs']],

            ['name' => 'Anganwadi Services - Honorarium to AWW and AWH', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Anganwadi Services - Supplementary Nutrition Program', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Scheme for Adolescent Girls', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'PALNA - Honorarium to Workers', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'PALNA - Facilities to Beneficiaries', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Mission Vatsalya - Salary of Staff', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Shakti Sadan (Swadhar and Ujjawala) - Salary', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Shakti Sadan (Swadhar and Ujawala) - Facilities to Beneficiaries', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Pradhan Mantri Matru Vandana Yojana', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Anganwadi Services - Training Program', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'One Stop Centre (Payment of Salary of Staff)', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Mission Vatsalya - Facilities to Beneficiaries', 'department_id' => $departmentIds['Ministry of Women and Child Development']],
            ['name' => 'Mission Vatsalya - Facilities to Beneficiaries (Sponsorship)', 'department_id' => $departmentIds['Ministry of Women and Child Development']],

        ];

        DB::table('schemes')->insert($schemes);
    }
}
